executable = /bin/singularity
arguments = exec --bind /var/lib/condor:/var/lib/condor  --home /home/patrick.miles:/srv /cvmfs/singularity.opensciencegrid.org/patrickrmiles/j0030:analysis_v0.3 /srv/j0030/nicer/run_j0030_test.sh

log = output/run_j0030_test.$(cluster).log
output = output/run_j0030_test.$(cluster).out
error = output/run_j0030_test.$(cluster).err

request_cpus = 40

requirements = HasSingularity == true
queue 1
